apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-dependencies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-gitops-repo.git'
    targetRevision: main
    path: apps  # Folder containing the YAML files
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
