apiVersion: components.platform.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '3'
  name: model-registry
  namespace: rhoai-model-registries
spec:
  grpc:
    port: 9090
  istio:
    gateway:
      grpc:
        gatewayRoute: enabled
        port: 443
        tls:
          mode: SIMPLE
      istioIngress: ingressgateway
      rest:
        gatewayRoute: enabled
        port: 443
        tls:
          mode: SIMPLE
    tlsMode: ISTIO_MUTUAL
  mysql:
    database: registry
    host: mysql.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db-secret
    port: 3306
    skipDBCreation: false
    username: mysql
  rest:
    port: 8080
    serviceRoute: disabled
