apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '3'
  name: my-model-registry
  namespace: rhoai-model-registries
spec:
  grpc:
    port: 9090
  mysql:
    database: registry
    host: mysql.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db-secret
    port: 3306
    skipDBCreation: false
    username: mysql
  oauthProxy:
    port: 8443
    routePort: 443
    serviceRoute: enabled
  rest:
    port: 8080
    serviceRoute: disabled
