kind: Secret
apiVersion: v1
metadata:
  name: model-registry-db-secret
  namespace: rhoai-model-registries
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: cmVnaXN0cnk=
  database-password: bXlzcWw=
  database-user: bXlzcWw=
type: Opaque
