apiVersion: modelregistry.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: model registry
  name: model-registry
  namespace: rhoai-model-registries
  finalizers:
    - modelregistry.opendatahub.io/finalizer
spec:
  grpc:
    port: 9090
  istio:
    gateway:
      grpc:
        gatewayRoute: enabled
        port: 443
        tls:
          mode: SIMPLE
      istioIngress: ingressgateway
      rest:
        gatewayRoute: enabled
        port: 443
        tls:
          mode: SIMPLE
    tlsMode: ISTIO_MUTUAL
  mysql:
    database: registry
    host: mysql.rhoai-model-registries.svc.cluster.local
    passwordSecret:
      key: database-password
      name: model-registry-db-secret
    port: 3306
    skipDBCreation: false
    username: mysql
  rest:
    port: 8080
    serviceRoute: disabled
---
kind: Secret
apiVersion: v1
metadata:
  name: model-registry-db-secret
  namespace: rhoai-model-registries
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: cmVnaXN0cnk=
  database-password: bXlzcWw=
  database-user: bXlzcWw=
type: Opaque
