kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: rhoai-model-registries
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: mysql
  template:
    metadata:
      labels:
        deployment: mysql
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: pvc-mysql
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: registry
            - name: MYSQL_DEFAULT_AUTHENTICATION_PLUGIN
              value: mysql_native_password
            - name: MYSQL_PASSWORD
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
            - name: MYSQL_USER
              value: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql/data
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhel8/mysql-80:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
