kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: rhoai-model-registries
  labels:
    app: mysql
    app.kubernetes.io/component: mysql
    app.kubernetes.io/instance: mysql
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    deployment: mysql
