apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: rhoai:/Namespace:redhat-ods-operator/redhat-ods-operator
    openshift.io/description: Red Hat OpenShift AI Operator
    openshift.io/display-name: RHOAI Operator
  name: redhat-ods-operator