# use this in a ds project to enable trusty server
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: TrustyAIService
metadata:
  name: trustyai-service
spec:
  data:
    filename: data.csv
    format: CSV
  metrics:
    batchSize: 5000
    schedule: 5s
  storage:
    folder: /inputs
    format: PVC
    size: 1Gi
