apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serverless
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/agroom/rhoai-argodc.git'
    targetRevision: main
    path: apps/serverless
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-serverless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
